### ISSUE TITLE
Fix incorrect error message

### ISSUE THREAD

**Issue by keithchong** [redhat-developer/gitops-cli#1]
**Describe the bug**
The error message that is presented to the user:
`The secret length should 16 or more`
is incorrect, and needs to be fixed.

**To Reproduce**
See Gagan's end of sprint review demo

<img width="696" alt="Screen Shot 2020-09-16 at 9 51 03 AM" src="https://user-images.githubusercontent.com/7726022/93779620-343a0b80-fbf5-11ea-9980-2b8289aa55c5.png">

**Expected behavior**
The message should be changed to something like:
`The length of the secret must be at least 16 characters`

I asked Jake from the Documentation team, and he suggested this:
`The secret's length must be 16 characters or more`

**Comment by jc-berger** [comment]
The doc team approves Keith's revision and thinks the sentence ought to be change to,
`The length of the secret must be at least 16 characters`
